# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [6]:
#code here
import numpy as np
arr=np.random.randint(0,24,12)
arr2=arr.reshape(3,4)
print("Arr 1: {}".format(arr))
print("Arr 2: {}".format(arr2))

arr=np.arange(5)
arr2=np.arange(5)
horizontal=np.concatenate((arr,arr2))
print("Horizontal: {}".format(horizontal))
print("\n")
vertical=np.concatenate((arr.reshape(-1,1),arr2.reshape(-1,1)))
print("Vertical: {}".format(vertical))

vertical2=np.concatenate((arr,arr2)).reshape(2,-1)
print("Other form of Vertical Concatenation: \n{}".format(vertical2))


Arr 1: [12  2  5  2  2 20 18 23  1  6 23  4]
Arr 2: [[12  2  5  2]
 [ 2 20 18 23]
 [ 1  6 23  4]]
Horizontal: [0 1 2 3 4 0 1 2 3 4]


Vertical: [[0]
 [1]
 [2]
 [3]
 [4]
 [0]
 [1]
 [2]
 [3]
 [4]]
Other form of Vertical Concatenation: 
[[0 1 2 3 4]
 [0 1 2 3 4]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [14]:
#code here
def classify_emails(emails):
  imp=['important','urgent']
  promo=['offer','discount','sale']
  spam=['lottery','free']

  imp_emails=[]
  promo_emails=[]
  spam_emails=[]

  for email in emails:
    is_imp=False
    is_promo=False
    is_spam=False
    email_lower=email.lower()
    for word in imp:
      if word in email_lower:
        is_imp=True
        break
    for word in promo:
      if word in email_lower:
        is_promo=True
        break
    for word in spam:
      if word in email_lower:
        is_spam=True
        break

    if is_imp:
      imp_emails.append(email)
    elif is_promo:
      promo_emails.append(email)
    elif is_spam:
      spam_emails.append(email)

  return imp_emails,promo_emails,spam_emails


emails=["You've won a Free Iphone 15",
        "Sale starting from 20th February",
        "Important announcement! Deadline due tomorrow",
        "15% discount on all clothes"]

imp_emails,promo_emails,spam_emails=classify_emails(emails)
print("Important Emails: \n{}".format(imp_emails))
print("Promotional Emails: \n{}".format(promo_emails))
print("Spam Emails: \n{}".format(spam_emails))

Important Emails: 
['Important announcement! Deadline due tomorrow']
Promotional Emails: 
['Sale starting from 20th February', '15% discount on all clothes']
Spam Emails: 
["You've won a Free Iphone 15"]


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [16]:
#code here
def Checker(word,translation_dictionary):
  if word in translation_dictionary:
    return translation_dictionary[word]
  else:
    return False

translation_dictionary={
    "hello":"hola",
    "cat":"gato",
    "friend":"amigo",
    "bye":"adios",
    "class":"clase",
    "teacher":"maestro",
    "yes":"si",
    "no":"no"
}

while True:
  word=input("Enter an english word (Press Q to exit): ")
  word=word.lower()
  if word=="q":
    print("Program ended. GoodBye!")
    break
  spanish_translation=Checker(word,translation_dictionary)
  if spanish_translation:
    print("The Spanish Translation of {} is {}\n".format(word,spanish_translation))
  else:
    print("The Spanish Translation of {} is not available in the dictionary".format(word))

Enter an english word (Press Q to exit): yes
The Spanish Translation of yes is si

Enter an english word (Press Q to exit): no
The Spanish Translation of no is no

Enter an english word (Press Q to exit): Q
Program ended. GoodBye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [4]:
import pandas as pd
url='https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv'
df=pd.read_csv(url)
df


Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [5]:
# Calculate the total global sales for all games in the dataset.
global_sales=df['Global_Sales'].sum()
print("Sum of Global Sales: {}".format(global_sales))

Sum of Global Sales: 8920.44


In [7]:
# Find the game with the highest global sales.
highest_idx=df['Global_Sales'].idxmax()
highest_game=df.loc[highest_idx]
print("Game with highest Global Sales: {}".format(highest_game))

Game with highest Global Sales: Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object


In [9]:
# Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
avg_sales = df[['NA_Sales','EU_Sales', 'JP_Sales','Other_Sales']].mean()
print("Average sales for each region:")
print(avg_sales)

Average sales for each region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [10]:
# Find the top 5 most popular game genres based on global sales.
grouped_genre=df.groupby('Genre')['Global_Sales'].sum()
top5_genre=grouped_genre.nlargest(5)
print("Top 5 Genres based on Global Sales: {}".format(top5_genre))

Top 5 Genres based on Global Sales: Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [13]:
# Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
total_sales=df.groupby("Genre")[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum()
popular_genre =total_sales['NA_Sales'].idxmax()
print("Most popular genre in North America (NA_Sales):",popular_genre)


Most popular genre in North America (NA_Sales): Action


In [14]:
# Display last 10 rows.
last_rows=df.tail(10)
last_rows

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [15]:
# Determine the top 3 gaming platforms with the highest global sales.
grouped_platforms=df.groupby('Platform')['Global_Sales'].sum()
top3_platforms=grouped_platforms.nlargest(3)
print("Top 3 Gaming platforms with highest Global Sales: {}".format(top3_platforms))

Top 3 Gaming platforms with highest Global Sales: Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [19]:
# Calculate the market share (percentage of global sales) for each genre.
grouped_genre=df.groupby('Genre')['Global_Sales'].sum()
global_sales=df['Global_Sales'].sum()
market_share=(grouped_genre/global_sales)*100
print("Market Share for each genre: {}".format(market_share))

Market Share for each genre: Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


Some tree example

In [20]:
# Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)
corr_coefficient=df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation of cofficient between NA Sales and EU Sales: {}".format(corr_coefficient))

Correlation of cofficient between NA Sales and EU Sales: 0.7677267483702634


In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
